export const OK_STATUS = 200
export const BAD_REQUEST_STATUS = 400
export const NOT_FOUND_STATUS = 404
export const INTERNAL_SERVER_STATUS = 500
export const NOT_CHANGED_STATUS = 304
export const FORBIDDEN_STATUS = 403
export const NOT_AUTHORIZED_STATUS = 401
export const ALREADY_EXISTS_STATUS = 409